source 'https://github.com/brightcove/BrightcoveSpecs.git'

use_frameworks!

platform :ios, '11.0' # (or whatever version you want)

target 'Simple-Video-Playback' do
	pod 'Brightcove-Player-Core', '6.3.11'
end
